version: 2.0.3.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
   
platform: Any CPU   
   
configuration: Release   
   
build:
  project: DbTestMonkey.sln
  publish_nuget: true
  publish_nuget_symbols: true

before_build:
  - nuget restore
  
deploy:
  - provider: NuGet
    api_key:
      secure: NiJcbCyOcMrqDb8qUO30VdjNUP0X644sSq1eJWatSCk0YgyqePcxD4OsiN2Nw4vc
    skip_symbols: false
    artifact: /.*\.nupkg/
    on:
      branch: master
      appveyor_repo_tag: true
